export default () => ({
    mobileMenuOpen: false, 
    scrolled: false,
    lang: 'es', // Default to Spanish as it is a Seville hacienda
    translations: {
        en: {
            nav_legend: 'History',
            nav_spaces: 'Spaces',
            nav_inquire: 'Inquire',
            hero_est: 'Est. XVI Century',
            hero_title1: 'SUN.',
            hero_title2: 'STONE.',
            hero_title3: 'CELEBRATION.',
            hero_subtitle: 'Where history becomes your backdrop.',
            hero_cta: 'Explore',
            legacy_section_title: 'The Legacy',
            legacy_heading_1: 'Shadow',
            legacy_heading_2: '& Light',
            legacy_text_1: 'Some places are merely venues. This one has a story—and now it\'s ready for yours. Walls that have stood since the conquistadors returned. An olive oil mill that crushed fruit for empires.',
            legacy_text_2: 'We stripped away the plaster to reveal the soul of the building. Raw brick. Ancient stone. This is not a venue dressed up for a party. It is history inviting you to celebrate.',
            spaces_section_title: 'The Stage',
            spaces_subtitle: 'Choose your backdrop',
            space_almazara: 'The Almazara',
            space_almazara_desc: 'Vast. Vaulted. Visceral. The old oil mill reborn. High ceilings that catch the echo of laughter. Perfect when the guest list is immense and the impression must be absolute.',
            space_almazara_cap: 'Capacity: 500+',
            space_almazara_type: 'Type: Indoor / Grand Hall',
            space_gardens: 'The Gardens',
            space_gardens_desc: 'Nature as the architect. Patios paved with history, surrounded by jasmine and the scent of centuries. A setting that requires no decoration, only appreciation.',
            space_gardens_cap: 'Capacity: 800+',
            space_gardens_type: 'Type: Open Air / Historical Patios',
            footer_cta1: 'RESERVE YOUR',
            footer_cta2: 'DATE',
            footer_title: 'Your Chapter Begins',
            footer_role: 'Event Director',
            footer_location: 'Location',
            footer_social: 'Social',
            history_hero_title: 'Andalusian Legacy',
            history_hero_subtitle: 'Architecture of Olive Oil and Silence',
            weddings_hero_title: 'A Historical Novel',
            weddings_hero_subtitle: 'Not a Fairy Tale',
            corporate_hero_title: 'Disconnect to Reconnect',
            corporate_hero_subtitle: 'Retreats & Events',
            nav_discover_history: 'Discover History',
            weddings_ceremony_title: 'The Ceremony',
            weddings_ceremony_text: 'Forget the plastic \"happily ever after\". This is a stone structure that has seen centuries. Our patios are not sets; they are stages of gravity and light.',
            corporate_focus_title: 'Isolation Fosters Focus',
            corporate_focus_text: 'In a world of constant notifications, true luxury is silence. Hacienda La Soledad offers an austere yet sublime environment where teams can disconnect from the noise to reconnect with their purpose.',
            history_intro_title: 'Socio-Economic Palimpsest',
            history_intro_text: 'More than a simple construction, Hacienda La Soledad is a cross-section of Andalusian history.',
            history_timeline_title: 'Secular Chronicle',
            history_timeline_1_title: 'Foundation',
            history_timeline_2_title: 'Commercial Heyday',
            history_timeline_3_title: 'The Great Reconstruction',
            history_timeline_4_title: 'War & Ruin',
            history_timeline_5_title: 'The Golden Age',
            weddings_celebration_title: 'The Celebration',
            weddings_celebration_text: 'The Almazara, with its vaulted ceilings and perfect acoustics, transforms into the ultimate ballroom. Capacity for large banquets without losing the atmosphere of exclusivity. Every corner is designed to impress, not by its decoration, but by its authenticity.',
            weddings_corners_title: 'Our Corners',
            corporate_efficiency_title: 'Efficiency',
            corporate_efficiency_text: 'Fast responses. Minimal bureaucracy. We understand that a corporate event is not a wedding; it is an investment. Clear dossiers, technical plans ready, and a team that speaks the language of business.',
            corporate_character_title: 'Character',
            corporate_character_text: 'Replace sterile conference rooms with 16th-century walls. Inspire your executives with the gravity of history. The architecture here does not decorate; it commands respect.',
            corporate_map_title: 'Hacienda Plan',
            corporate_map_text: 'Get to know the exact distribution of our 10,000m² of versatile spaces.',
            corporate_view_detail: 'View Detail',
            corporate_download_map: 'Download Technical Plan (PDF)',
            corporate_mice_title: 'MICE & Team Building',
            corporate_mice_text: 'From large-scale conventions in our Almazara to intimate executive retreats in the gardens. Absolute capacity and versatility.',
            corporate_request_dossier: 'Request Business Dossier',
            corporate_trusted_by: 'Trusted by Us',
            spaces_indoor_title: 'Indoor Spaces',
            spaces_indoor_subtitle: 'Climate controlled. Historic ceilings. Unmatched atmosphere.',
            spaces_outdoor_title: 'Patios & Gardens',
            spaces_outdoor_subtitle: 'Albero. Stone. Open sky.',
            spaces_tech_title: 'Technical Specifications',
            spaces_tech_dossier: 'Download Technical Dossier',
            label_cocktail: 'Cocktail',
            label_banquet: 'Banquet',
            label_area: 'Area',
            label_height: 'Height',
            label_capacity: 'Capacity',
            label_indoor_desc: 'Climate controlled. Historic ceilings. Unmatched atmosphere.',
            label_outdoor_desc: 'Albero. Stone. Open sky.',
            availability_title: 'Availability',
            availability_subtitle: 'Check available dates for your celebration. Dates in green are available for booking.',
            availability_available: 'Available',
            availability_booked: 'Booked',
            availability_consultation: 'In consultation',
            availability_past: 'Past',
            availability_request_info: 'Request Information',
            availability_whatsapp: 'Direct WhatsApp',
            availability_selected_intro: 'This date is available. Would you like to request more information?',
            index_bridge_title: 'Two worlds, one roof.',
            index_bridge_subtitle: 'Privacy for few. Grandeur for many.',
            index_weddings_title: 'Royal Weddings',
            index_weddings_text: 'Celebrate your union in a historical sanctuary. From the vaulted Almazara to the jasmine-filled patios.',
            index_weddings_cta: 'View Weddings',
            index_corporate_title: 'Corporate Events',
            index_corporate_text: 'Disconnect to reconnect. Executive retreats and product launches in an inspiring environment.',
            index_corporate_cta: 'View Businesses',
            index_follow_us: 'Follow Us',
            index_insta_placeholder: 'Your Instagram feed will appear here',
            index_visit_profile: 'Visit Profile',
            history_location: 'Location',
            history_foundation: 'Foundation',
            history_apex: 'Apex',
            history_status: 'Status',
            history_bic: 'Cultural Heritage (BIC)',
            history_intro_text_2: 'Here, global flows of oil trade intersect with local traditions, creating a \"field factory\" that also served as a pleasure palace.',
            history_timeline_1_desc: 'Rodrigo de Espinosa, banker to Charles V, buys the estate. His family controls the oil and soap trade to the Indies.',
            history_timeline_2_desc: 'Under Alonso de Ayala, the hacienda reaches its maximum production. Thousands of oil units exported to Flanders and America.',
            history_timeline_3_desc: 'Don Adrián Delgado Ayala, Knight of Santiago, rebuilds the farmhouse \"from its foundations\". Current Baroque layout is born.',
            history_timeline_4_desc: 'The English naval blockade of Cadiz cuts Atlantic routes. Without exports, Ayala goes bankrupt.',
            history_timeline_5_desc: 'The Gómez de Barreda family acquires the estate. The Cruiser Garden and horse frescoes are added.',
            history_timeline_modern: '21st Century',
            history_timeline_rebirth: 'Rebirth',
            history_timeline_rebirth_desc: 'Under the custody of the Maestre Benjumea brothers, original esgrafiados are revealed. Transition to the \"experience economy\".',
            history_anatomy_title: 'Anatomy of a Hacienda',
            history_anatomy_subtitle: 'The perfect fusion between industrial strength and residential palace.',
            history_arch_almazara: 'The Almazara',
            history_arch_tower: 'Counterweight Tower',
            history_arch_patios: 'Patio System',
            history_arch_capilla: 'The Chapel',
            history_almazara_title: 'The Liquid Gold Factory',
            history_almazara_desc: 'This immense nave housed the \"spindle beam\", a 15-meter wooden leviathan. Here, the smell of olives and the work of beasts dominated.',
            history_tower_title: 'Counterweight Tower',
            history_tower_desc: 'The \"skyscrapers\" of the Andalusian countryside. Pure physics to anchor the counterweight that lifted the giant press beam.',
            history_patios_title: 'Spatial Segregation',
            history_patios_desc: 'Architecture imposes social order. The Labor Patio (2000 m²) bustles with activity, while the Lordship Patio remains an introverted cloister.',
            history_capilla_title: 'Private Oratory',
            history_capilla_desc: 'With its altarpiece and Marian tiles, the chapel legitimized the owners\' piety and served to impose the liturgical cycle.',
            history_economy_title: 'Oil Economy',
            history_production_mode: 'XVIII Century Production',
            history_labor_mode: 'Labor Cycle',
            history_chart_note: '*Estimated historical data based on Los Alcores registries.',
            history_social_title: 'Social Stratification',
            history_lordship: 'The Lordship (Señorío)',
            history_lordship_rank: 'Aristocracy',
            history_lordship_desc: 'Absentee owners living in Seville. The hacienda was their status symbol and summer retreat.',
            history_housekeeper: 'The Housekeeper (Casero)',
            history_housekeeper_rank: 'Management',
            history_housekeeper_desc: 'The present authority. Guardian of the granary and mill keys. Crucial intermediary.',
            history_laborers: 'The Laborers (Gañanía)',
            history_laborers_rank: 'Labor Force',
            history_laborers_desc: 'Seasonal olive pickers and shepherds living in communal dormitories. A hard life marked by the bell.'
        },
        es: {
            nav_legend: 'Historia',
            nav_spaces: 'Espacios',
            nav_inquire: 'Contactar',
            hero_est: 'Est. Siglo XVI',
            hero_title1: 'SOL.',
            hero_title2: 'PIEDRA.',
            hero_title3: 'CELEBRACIÓN.',
            hero_subtitle: 'Donde la historia se convierte en tu escenario.',
            hero_cta: 'Explorar',
            legacy_section_title: 'El Legado',
            legacy_heading_1: 'Sombra',
            legacy_heading_2: 'y Luz',
            legacy_text_1: 'Algunos lugares son solo espacios. Este tiene una historia—y ahora está listo para la tuya. Muros que han permanecido desde el regreso de los conquistadores. Una almazara que prensó el fruto para imperios.',
            legacy_text_2: 'Quitamos el yeso para revelar el alma del edificio. Ladrillo crudo. Piedra antigua. Esto no es un salón de fiestas disfrazado. Es la historia invitándote a celebrar.',
            spaces_section_title: 'El Escenario',
            spaces_subtitle: 'Elige tu telón de fondo',
            space_almazara: 'La Almazara',
            space_almazara_desc: 'Vasta. Abovedada. Visceral. El antiguo molino renacido. Techos altos que capturan el eco de las risas. Perfecto cuando la lista de invitados es inmensa y la impresión debe ser absoluta.',
            space_almazara_cap: 'Capacidad: 500+',
            space_almazara_type: 'Tipo: Interior / Gran Salón',
            space_gardens: 'Los Jardines',
            space_gardens_desc: 'La naturaleza como arquitecto. Patios pavimentados con historia, rodeados de jazmín y el aroma de los siglos. Un escenario que no requiere decoración, solo admiración.',
            space_gardens_cap: 'Capacidad: 800+',
            space_gardens_type: 'Tipo: Aire Libre / Patios Históricos',
            footer_cta1: 'RESERVA TU',
            footer_cta2: 'FECHA',
            footer_title: 'Tu Capítulo Comienza',
            footer_role: 'Directora de Eventos',
            footer_location: 'Ubicación',
            footer_social: 'Redes',
            history_hero_title: 'Legado Andaluz',
            history_hero_subtitle: 'Arquitectura del Aceite y el Silencio',
            weddings_hero_title: 'Una Novela Histórica',
            weddings_hero_subtitle: 'No es un cuento de hadas',
            corporate_hero_title: 'Disconnect to Reconnect',
            corporate_hero_subtitle: 'Retiros & Eventos Corporativos',
            nav_discover_history: 'Descubrir Historia',
            weddings_ceremony_title: 'La Ceremonia',
            weddings_ceremony_text: 'Olvida el \"vivieron felices para siempre\" de plástico. Esto es una estructura de piedra que ha visto siglos. Nuestros patios no son decorados; son escenarios de gravedad y luz.',
            corporate_focus_title: 'El Aislamiento Fomenta la Concentración',
            corporate_focus_text: 'En un mundo de notificaciones constantes, el verdadero lujo es el silencio. Hacienda La Soledad ofrece un entorno austero pero sublime donde los equipos pueden desconectar del ruido para reconectar con su propósito.',
            history_intro_title: 'Palimpsesto Socio-Económico',
            history_intro_text: 'Más que una simple construcción, la Hacienda de la Soledad es una sección transversal de la historia andaluza.',
            history_timeline_title: 'Crónica Secular',
            history_timeline_1_title: 'Fundación',
            history_timeline_2_title: 'Apogeo Comercial',
            history_timeline_3_title: 'La Gran Reconstrucción',
            history_timeline_4_title: 'Guerra y Ruina',
            history_timeline_5_title: 'La Edad de Oro',
            weddings_celebration_title: 'La Celebración',
            weddings_celebration_text: 'La Almazara, con sus techos abovedados y acústica perfecta, se transforma en el salón de baile definitivo. Capacidad para grandes banquetes sin perder la atmósfera de exclusividad. Cada rincón está diseñado para impresionar, no por su decoración, sino por su autenticidad.',
            weddings_corners_title: 'Nuestros Rincones',
            corporate_efficiency_title: 'Eficiencia',
            corporate_efficiency_text: 'Respuestas rápidas. Burocracia mínima. Entendemos que un evento corporativo no es una boda; es una inversión. Dossiers claros, planos técnicos listos, y un equipo que habla el idioma de los negocios.',
            corporate_character_title: 'Carácter',
            corporate_character_text: 'Sustituya las salas de conferencias estériles por muros del siglo XVI. Inspire a sus ejecutivos con la gravedad de la historia. La arquitectura aquí no decora; impone respeto.',
            corporate_map_title: 'Plano de la Hacienda',
            corporate_map_text: 'Conozca la distribución exacta de nuestros 10.000m² de espacios versátiles.',
            corporate_view_detail: 'Ver Detalle',
            corporate_download_map: 'Descargar Plano Técnico (PDF)',
            corporate_mice_title: 'MICE & Team Building',
            corporate_mice_text: 'Desde convenciones a gran escala en nuestra Almazara hasta retiros directivos íntimos en los jardines. Capacidad y versatilidad absoluta.',
            corporate_request_dossier: 'Solicitar Dossier Empresas',
            corporate_trusted_by: 'Confían en Nosotros',
            spaces_indoor_title: 'Espacios Interiores',
            spaces_indoor_subtitle: 'Climatizados. Techos históricos. Atmósfera inigualable.',
            spaces_outdoor_title: 'Patios y Jardines',
            spaces_outdoor_subtitle: 'Albero. Piedra. Cielo abierto.',
            spaces_tech_title: 'Especificaciones Técnicas',
            spaces_tech_dossier: 'Descargar Dossier Técnico',
            label_cocktail: 'Cóctel',
            label_banquet: 'Banquete',
            label_area: 'Área',
            label_height: 'Altura',
            label_capacity: 'Capacidad',
            label_indoor_desc: 'Climatizados. Techos históricos. Atmósfera inigualable.',
            label_outdoor_desc: 'Albero. Piedra. Cielo abierto.',
            availability_title: 'Disponibilidad',
            availability_subtitle: 'Consulta las fechas disponibles para tu celebración. Las fechas en verde están disponibles para reserva.',
            availability_available: 'Disponible',
            availability_booked: 'Reservado',
            availability_consultation: 'En consulta',
            availability_past: 'Pasado',
            availability_request_info: 'Solicitar Información',
            availability_whatsapp: 'WhatsApp Directo',
            availability_selected_intro: 'Esta fecha está disponible. ¿Te gustaría solicitar más información?',
            index_bridge_title: 'Dos mundos, un mismo techo.',
            index_bridge_subtitle: 'Intimidad para pocos. Grandeza para muchos.',
            index_weddings_title: 'Bodas Reales',
            index_weddings_text: 'Celebra tu unión en un santuario histórico. Desde la Almazara abovedada hasta los patios llenos de jazmín.',
            index_weddings_cta: 'Ver Bodas',
            index_corporate_title: 'Eventos Corporativos',
            index_corporate_text: 'Disconnect to reconnect. Retiros ejecutivos y presentaciones de producto en un entorno inspirador.',
            index_corporate_cta: 'Ver Empresas',
            index_follow_us: 'Síguenos',
            index_insta_placeholder: 'Tu feed de Instagram aparecerá aquí',
            index_visit_profile: 'Visitar Perfil',
            history_location: 'Ubicación',
            history_foundation: 'Fundación',
            history_apex: 'Apogeo',
            history_status: 'Estatuto',
            history_bic: 'Bien de Interés Cultural',
            history_intro_text_2: 'Aquí, los flujos globales del comercio de jabón y aceite se cruzaron con las tradiciones locales, creando una \"fábrica de campo\" que también sirvió como palacio de recreo.',
            history_timeline_1_desc: 'Rodrigo de Espinosa, banquero de Carlos V, compra la finca. Su familia controla el comercio de aceite y jabón desde Sevilla hacia las Indias.',
            history_timeline_2_desc: 'Bajo Alonso de Ayala, la hacienda alcanza su máximo productivo. Se exportan miles de arrobas de aceite a Flandes y América.',
            history_timeline_3_desc: 'Don Adrián Delgado Ayala, Caballero de Santiago, reconstruye el cortijo \"desde sus cimientos\". Nace la traza barroca actual.',
            history_timeline_4_desc: 'El bloqueo naval inglés de Cádiz corta las rutas atlánticas. Sin poder exportar aceite y jabón, Ayala quiebra.',
            history_timeline_5_desc: 'La familia Gómez de Barreda adquiere la finca. Se añaden el Jardín de Crucero y los frescos de caballos.',
            history_timeline_modern: 'Siglo XXI',
            history_timeline_rebirth: 'Renacimiento',
            history_timeline_rebirth_desc: 'Bajo la custodia de los hermanos Maestre Benjumea, se revelan los esgrafiados originales. Transición a la \"economía de la experiencia\".',
            history_anatomy_title: 'Anatomía de una Hacienda',
            history_anatomy_subtitle: 'La fusión perfecta entre fortaleza industrial y palacio residencial.',
            history_arch_almazara: 'La Almazara',
            history_arch_tower: 'Torre de Contrapeso',
            history_arch_patios: 'Sistema de Patios',
            history_arch_capilla: 'La Capilla',
            history_almazara_title: 'La Fábrica de Oro Líquido',
            history_almazara_desc: 'Esta inmensa nave albergaba la \"viga de husillo\", un leviatán de madera de 15 metros. Aquí, el ruido de las bestias y el olor a alpechín dominaban.',
            history_tower_title: 'Torre de Contrapeso',
            history_tower_desc: 'Los \"rascacielos\" del campo andaluz. Pura física para anclar el contrapeso que levantaba la gigantesca viga de la prensa.',
            history_patios_title: 'Segregación Espacial',
            history_patios_desc: 'La arquitectura impone orden social. El Patio de Labor (2000 m²) bulle de actividad, mientras el Patio del Señorío permanece como un claustro introvertido.',
            history_capilla_title: 'Oratorio Privado',
            history_capilla_desc: 'Con su retablo de estípites y azulejos marianos, la capilla legitimaba la piedad de los dueños y servía para imponer el ciclo litúrgico.',
            history_economy_title: 'Economía del Aceite',
            history_production_mode: 'Producción S.XVIII',
            history_labor_mode: 'Ciclo Laboral',
            history_chart_note: '*Datos históricos estimados basados en registros de Los Alcores.',
            history_social_title: 'Estratificación Social',
            history_lordship: 'El Señorío',
            history_lordship_rank: 'Aristocracia',
            history_lordship_desc: 'Propietarios absentistas residiendo en Sevilla. La hacienda era su símbolo de estatus y retiro estival.',
            history_housekeeper: 'El Casero',
            history_housekeeper_rank: 'Gestión',
            history_housekeeper_desc: 'La autoridad presente. Guardián de las llaves del granero y el molino. Intermediario crucial.',
            history_laborers: 'La Gañanía',
            history_laborers_rank: 'Mano de Obra',
            history_laborers_desc: 'Aceituneros estacionales y pastores viviendo en dormitorios comunales. Una vida dura marcada por la campana.'
        },
        fr: {
            nav_legend: 'Histoire',
            nav_spaces: 'Espaces',
            nav_inquire: 'Contact',
            hero_est: 'Fondée au XVIe Siècle',
            hero_title1: 'SOLEIL.',
            hero_title2: 'PIERRE.',
            hero_title3: 'CÉLÉBRATION.',
            hero_subtitle: 'Où l\'histoire devient votre décor.',
            hero_cta: 'Découvrir',
            legacy_section_title: 'L\'Héritage',
            legacy_heading_1: 'Ombre',
            legacy_heading_2: 'et Lumière',
            legacy_text_1: 'Certains lieux ne sont que des espaces. Celui-ci a une histoire—et maintenant, il est prêt pour la vôtre. Des murs debout depuis le retour des conquistadors. Un moulin à huile qui broyait les fruits pour des empires.',
            legacy_text_2: 'Nous avons retiré le plâtre pour révéler l\'âme du bâtiment. Brique brute. Pierre ancienne. Ce n\'est pas une salle de réception déguisée. C\'est l\'histoire qui vous invite à célébrer.',
            spaces_section_title: 'La Scène',
            spaces_subtitle: 'Choisissez votre décor',
            space_almazara: 'L\'Almazara',
            space_almazara_desc: 'Vaste. Voûtée. Viscérale. L\'ancien moulin renaît. De hauts plafonds qui capturent l\'écho des rires. Parfait quand la liste des invités est immense et l\'impression doit être absolue.',
            space_almazara_cap: 'Capacité : 500+',
            space_almazara_type: 'Type : Intérieur / Grande Salle',
            space_gardens: 'Les Jardins',
            space_gardens_desc: 'La nature comme architecte. Des patios pavés d\'histoire, entourés de jasmin et du parfum des siècles. Un cadre qui n\'exige aucune décoration, seulement de l\'admiration.',
            space_gardens_cap: 'Capacité : 800+',
            space_gardens_type: 'Type : Plein Air / Patios Historiques',
            footer_cta1: 'RÉSERVEZ VOTRE',
            footer_cta2: 'DATE',
            footer_title: 'Votre Chapitre Commence',
            footer_role: 'Directrice Événementielle',
            footer_location: 'Adresse',
            footer_social: 'Réseaux',
            history_hero_title: 'Héritage Andalou',
            history_hero_subtitle: 'Architecture de l\'Huile d\'Olive et du Silence',
            weddings_hero_title: 'Un Roman Historique',
            weddings_hero_subtitle: 'Pas un conte de fées',
            corporate_hero_title: 'Se déconnecter pour se reconnecter',
            corporate_hero_subtitle: 'Retraites & Événements d\'entreprise',
            nav_discover_history: 'Découvrir l\'Histoire',
            weddings_ceremony_title: 'La Cérémonie',
            weddings_ceremony_text: 'Oubliez le \"ils vécurent heureux\" en plastique. C\'est une structure en pierre qui a vu passer les siècles. Nos patios ne sont pas des décors ; ce sont des scènes de gravité et de lumière.',
            corporate_focus_title: 'L\'isolement favorise la concentration',
            corporate_focus_text: 'Dans un monde de notifications constantes, le vrai luxe est le silence. La Hacienda La Soledad offre un environnement austère mais sublime où les équipes peuvent se déconnecter du bruit pour se reconnecter à leur objectif.',
            history_intro_title: 'Palimpseste socio-économique',
            history_intro_text: 'Plus qu\'une simple construction, la Hacienda de la Soledad est une coupe transversale de l\'histoire andalouse.',
            history_timeline_title: 'Chronique Séculaire',
            history_timeline_1_title: 'Fondation',
            history_timeline_2_title: 'Apogée Commercial',
            history_timeline_3_title: 'La Grande Reconstruction',
            history_timeline_4_title: 'Guerre et Ruine',
            history_timeline_5_title: 'L\'Âge d\'Or',
            weddings_celebration_title: 'La Célébration',
            weddings_celebration_text: 'L\'Almazara, avec ses plafonds voûtés et son acoustique parfaite, se transforme en l\'ultime salle de bal. Capacité pour de grands banquets sans perdre l\'atmosphère d\'exclusivité. Chaque coin est conçu pour impressionner, non par sa décoration, mais par son authenticité.',
            weddings_corners_title: 'Nos Coins',
            corporate_efficiency_title: 'Efficacité',
            corporate_efficiency_text: 'Réponses rapides. Bureaucratie minimale. Nous comprenons qu\'un événement d\'entreprise n\'est pas un mariage ; c\'est un investissement. Des dossiers clairs, des plans techniques prêts et une équipe qui parle la langue des affaires.',
            corporate_character_title: 'Caractère',
            corporate_character_text: 'Remplacez les salles de conférence stériles par des murs du XVIe siècle. Inspirez vos cadres avec la gravité de l\'histoire. Ici, l\'architecture ne décore pas ; elle impose le respect.',
            corporate_map_title: 'Plan de la Hacienda',
            corporate_map_text: 'Découvrez la distribution exacte de nos 10 000 m² d\'espaces polyvalents.',
            corporate_view_detail: 'Voir le Détail',
            corporate_download_map: 'Télécharger le Plan Technique (PDF)',
            corporate_mice_title: 'MICE & Team Building',
            corporate_mice_text: 'Des conventions à grande échelle dans notre Almazara aux retraites de direction intimes dans les jardins. Capacité et polyvalence absolues.',
            corporate_request_dossier: 'Demander un Dossier Entreprise',
            corporate_trusted_by: 'Ils nous font confiance',
            spaces_indoor_title: 'Espaces Intérieurs',
            spaces_indoor_subtitle: 'Climatisés. Plafonds historiques. Atmosphère inégalée.',
            spaces_outdoor_title: 'Patios et Jardins',
            spaces_outdoor_subtitle: 'Albero. Pierre. Ciel ouvert.',
            spaces_tech_title: 'Spécifications Techniques',
            spaces_tech_dossier: 'Télécharger le Dossier Technique',
            label_cocktail: 'Cocktail',
            label_banquet: 'Banquet',
            label_area: 'Surface',
            label_height: 'Hauteur',
            label_capacity: 'Capacité',
            label_indoor_desc: 'Climatisés. Plafonds historiques. Atmosphère inégalée.',
            label_outdoor_desc: 'Albero. Pierre. Ciel ouvert.',
            availability_title: 'Disponibilité',
            availability_subtitle: 'Consultez les dates disponibles pour votre célébration. Les dates en vert sont disponibles pour réservation.',
            availability_available: 'Disponible',
            availability_booked: 'Réservé',
            availability_consultation: 'En consultation',
            availability_past: 'Passé',
            availability_request_info: 'Demander des Informations',
            availability_whatsapp: 'WhatsApp Direct',
            availability_selected_intro: 'Cette date est disponible. Souhaitez-vous demander plus d\'informations ?',
            index_bridge_title: 'Deux mondes, un seul toit.',
            index_bridge_subtitle: 'Intimité pour quelques-uns. Grandeur pour beaucoup.',
            index_weddings_title: 'Mariages Royaux',
            index_weddings_text: 'Célébrez votre union dans un sanctuaire historique. De l\'Almazara voûtée aux patios remplis de jasmin.',
            index_weddings_cta: 'Voir les Mariages',
            index_corporate_title: 'Événements d\'Entreprise',
            index_corporate_text: 'Déconnectez pour reconnecter. Retraites de direction et lancements de produits dans un cadre inspirant.',
            index_corporate_cta: 'Voir les Entreprises',
            index_follow_us: 'Suivez-nous',
            index_insta_placeholder: 'Votre flux Instagram apparaîtra ici',
            index_visit_profile: 'Visiter le Profil',
            history_location: 'Emplacement',
            history_foundation: 'Fondation',
            history_apex: 'Apogée',
            history_status: 'Statut',
            history_bic: 'Patrimoine Culturel (BIC)',
            history_intro_text_2: 'Ici, les flux mondiaux du commerce de l\'huile croisent les traditions locales, créant une \"usine de campagne\" qui servait aussi de palais.',
            history_timeline_1_desc: 'Rodrigo de Espinosa achete le domaine. Sa famille contrôle le commerce de l\'huile et du savon vers les Indes.',
            history_timeline_2_desc: 'Sous Alonso de Ayala, la hacienda atteint sa production maximale. Des milliers d\'unités d\'huile exportées vers les Flandres.',
            history_timeline_3_desc: 'Don Adrián Delgado Ayala reconstruit le corps de ferme \"depuis ses fondations\". Le tracé baroque actuel est né.',
            history_timeline_4_desc: 'Le blocus naval anglais de Cadix coupe les routes atlantiques. Sans exportations, Ayala fait faillite.',
            history_timeline_5_desc: 'La famille Gómez de Barreda acquiert le domaine. Le jardin du croiseur et les fresques de chevaux sont ajoutés.',
            history_timeline_modern: 'XXIe Siècle',
            history_timeline_rebirth: 'Renaissance',
            history_timeline_rebirth_desc: 'Sous la garde des frères Maestre Benjumea, les esgrafiados originaux sont révélés. Transition vers l\'économie de l\'expérience.',
            history_anatomy_title: 'Anatomie d\'une Hacienda',
            history_anatomy_subtitle: 'La fusion parfaite entre force industrielle et palais résidentiel.',
            history_arch_almazara: 'L\'Almazara',
            history_arch_tower: 'Tour de Contrepoids',
            history_arch_patios: 'Système de Patios',
            history_arch_capilla: 'La Chapelle',
            history_almazara_title: 'L\'Usine d\'Or Liquide',
            history_almazara_desc: 'Cette immense nef abritait la \"poutre fusiforme\", un léviathan en bois de 15 mètres.',
            history_tower_title: 'Tour de Contrepoids',
            history_tower_desc: 'Les \"gratte-ciel\" de la campagne andalouse. De la physique pure pour ancrer le contrepoids.',
            history_patios_title: 'Ségrégation Spatiale',
            history_patios_desc: 'L\'architecture impose l\'ordre social. Le Patio de Labor (2000 m²) fourmille d\'activité.',
            history_capilla_title: 'Oratoire Privé',
            history_capilla_desc: 'Avec son retable et ses tuiles mariales, la chapelle légitimait la piété des propriétaires.',
            history_economy_title: 'Économie de l\'Huile',
            history_production_mode: 'Production XVIIIe Siècle',
            history_labor_mode: 'Cycle de Travail',
            history_chart_note: '*Données historiques estimées.',
            history_social_title: 'Stratification Sociale',
            history_lordship: 'Le Seigneur (Señorío)',
            history_lordship_rank: 'Aristocratie',
            history_lordship_desc: 'Propriétaires absents résidant à Séville. La hacienda était leur symbole de statut.',
            history_housekeeper: 'Le Régisseur (Casero)',
            history_housekeeper_rank: 'Gestion',
            history_housekeeper_desc: 'L\'autorité présente. Gardien des clés du grenier et du moulin.',
            history_laborers: 'Les Ouvriers (Gañanía)',
            history_laborers_rank: 'Main-d\'œuvre',
            history_laborers_desc: 'Récolteurs d\'olives saisonniers vivant dans des dortoirs communaux.'
        },
        nl: {
            nav_legend: 'Geschiedenis',
            nav_spaces: 'Ruimtes',
            nav_inquire: 'Contact',
            hero_est: 'Gesticht in de 16e Eeuw',
            hero_title1: 'ZON.',
            hero_title2: 'STEEN.',
            hero_title3: 'VIERING.',
            hero_subtitle: 'Waar geschiedenis jouw achtergrond wordt.',
            hero_cta: 'Ontdekken',
            legacy_section_title: 'Het Erfgoed',
            legacy_heading_1: 'Schaduw',
            legacy_heading_2: 'en Licht',
            legacy_text_1: 'Sommige plaatsen zijn slechts ruimtes. Deze heeft een verhaal—en nu is het klaar voor dat van jou. Muren die overeind staan sinds de terugkeer van de conquistadores. Een olijfoliemolen die vruchten perste voor keizerrijken.',
            legacy_text_2: 'We hebben het pleisterwerk verwijderd om de ziel van het gebouw te onthullen. Ruwe baksteen. Oude steen. Dit is geen verklede feestzaal. Het is geschiedenis die je uitnodigt om te vieren.',
            spaces_section_title: 'Het Podium',
            spaces_subtitle: 'Kies jouw achtergrond',
            space_almazara: 'De Almazara',
            space_almazara_desc: 'Wijd. Gewelfd. Indrukwekkend. De oude olijfmolen herboren. Hoge plafonds die de echo van gelach vangen. Ideaal wanneer de gastenlijst enorm is en de indruk absoluut moet zijn.',
            space_almazara_cap: 'Capaciteit: 500+',
            space_almazara_type: 'Type: Binnen / Grote Zaal',
            space_gardens: 'De Tuinen',
            space_gardens_desc: 'De natuur als architect. Patio\'s geplaveid met geschiedenis, omringd door jasmijn en de geur van eeuwen. Een omgeving die geen decoratie nodig heeft, alleen waardering.',
            space_gardens_cap: 'Capaciteit: 800+',
            space_gardens_type: 'Type: Openlucht / Historische Patio\'s',
            footer_cta1: 'RESERVEER JE',
            footer_cta2: 'DATUM',
            footer_title: 'Jouw Hoofdstuk Begint',
            footer_role: 'Evenementenmanager',
            footer_location: 'Locatie',
            footer_social: 'Social Media',
            history_hero_title: 'Andalusisch Erfgoed',
            history_hero_subtitle: 'Architectuur van Olijfolie en Stilte',
            weddings_hero_title: 'Een Historische Roman',
            weddings_hero_subtitle: 'Geen Sprookje',
            corporate_hero_title: 'Ontkoppelen om weer te verbinden',
            corporate_hero_subtitle: 'Bedrijfsretraites & Evenementen',
            nav_discover_history: 'Ontdek Geschiedenis',
            weddings_ceremony_title: 'De Ceremonie',
            weddings_ceremony_text: 'Vergeet de plastic \"ze leefden nog lang en gelukkig\". Dit is een stenen structuur die eeuwen heeft gezien. Onze patio\'s zijn geen decors; het zijn podia van zwaartekracht en licht.',
            corporate_focus_title: 'Isolatie Bevordert Concentratie',
            corporate_focus_text: 'In een wereld van constante meldingen is echte luxe stilte. Hacienda La Soledad biedt een sobere maar sublieme omgeving waar teams zich kunnen loskoppelen van de ruis om opnieuw verbinding te maken met hun doel.',
            history_intro_title: 'Sociaal-Economisch Palimpsest',
            history_intro_text: 'Meer dan een eenvoudige constructie, Hacienda La Soledad is een dwarsdoorsnede van de Andalusische geschiedenis.',
            history_timeline_title: 'Seculiere Kroniek',
            history_timeline_1_title: 'Fundering',
            history_timeline_2_title: 'Commercieel Hoogtepunt',
            history_timeline_3_title: 'De Grote Reconstructie',
            history_timeline_4_title: 'Oorlog & Ruïne',
            history_timeline_5_title: 'De Gouden Eeuw',
            weddings_celebration_title: 'De Viering',
            weddings_celebration_text: 'De Almazara, met zijn gewelfde plafonds en perfecte akoestiek, verandert in de ultieme balzaal. Capaciteit voor grote banketten zonder de sfeer van exclusiviteit te verliezen. Elke hoek is ontworpen om indruk te maken, niet door de decoratie, maar door de authenticiteit.',
            weddings_corners_title: 'Onze Hoeken',
            corporate_efficiency_title: 'Efficiëntie',
            corporate_efficiency_text: 'Snelle reacties. Minimale bureaucratie. Wij begrijpen dat een bedrijfsevenement geen bruiloft is; het is een investering. Duidelijke dossiers, technische plannen klaar en een team dat de taal van het bedrijfsleven spreekt.',
            corporate_character_title: 'Karakter',
            corporate_character_text: 'Vervang steriele conferentieruimtes door 16e-eeuwse muren. Inspireer uw managers met de ernst van de geschiedenis. De architectuur hier decoreert niet; het dwingt respect af.',
            corporate_map_title: 'Hacienda Plan',
            corporate_map_text: 'Maak kennis met de exacte verdeling van onze 10.000 m² aan veelzijdige ruimtes.',
            corporate_view_detail: 'Bekijk Detail',
            corporate_download_map: 'Technische Tekening Downloaden (PDF)',
            corporate_mice_title: 'MICE & Teambuilding',
            corporate_mice_text: 'Van grootschalige congressen in onze Almazara tot intieme directie-retraites in de tuinen. Absolute capaciteit en veelzijdigheid.',
            corporate_request_dossier: 'Zakelijk Dossier Aanvragen',
            corporate_trusted_by: 'Vertrouwen op ons',
            spaces_indoor_title: 'Binnenruimtes',
            spaces_indoor_subtitle: 'Klimaatbeheersing. Historische plafonds. Ongeëvenaarde sfeer.',
            spaces_outdoor_title: 'Patio\'s en Tuinen',
            spaces_outdoor_subtitle: 'Albero. Steen. Open lucht.',
            spaces_tech_title: 'Technische Specificaties',
            spaces_tech_dossier: 'Technisch Dossier Downloaden',
            label_cocktail: 'Cocktail',
            label_banquet: 'Banket',
            label_area: 'Oppervlakte',
            label_height: 'Hoogte',
            label_capacity: 'Capaciteit',
            label_indoor_desc: 'Klimaatbeheersing. Historische plafonds. Ongeëvenaarde sfeer.',
            label_outdoor_desc: 'Albero. Steen. Open lucht.',
            availability_title: 'Beschikbaarheid',
            availability_subtitle: 'Bekijk de beschikbare data voor uw viering. Groen gemarkeerde data zijn beschikbaar voor reservering.',
            availability_available: 'Beschikbaar',
            availability_booked: 'Gereserveerd',
            availability_consultation: 'In aanvraag',
            availability_past: 'Verleden',
            availability_request_info: 'Informatie Aanvragen',
            availability_whatsapp: 'Direct WhatsApp',
            availability_selected_intro: 'Deze datum is beschikbaar. Wilt u meer informatie aanvragen?',
            index_bridge_title: 'Twee werelden, één dak.',
            index_bridge_subtitle: 'Privacy voor een paar. Grootheid voor velen.',
            index_weddings_title: 'Koninklijke Bruiloften',
            index_weddings_text: 'Vier uw verbintenis in een historisch heiligdom. Van de gewelfde Almazara tot de jasmijnrijke patio\'s.',
            index_weddings_cta: 'Bekijk Bruiloften',
            index_corporate_title: 'Zakelijke Evenementen',
            index_corporate_text: 'Disconnect to reconnect. Executive retraites en productlanceringen in een inspirerende omgeving.',
            index_corporate_cta: 'Bekijk Bedrijven',
            index_follow_us: 'Volg ons',
            index_insta_placeholder: 'Uw Instagram-feed verschijnt hier',
            index_visit_profile: 'Bezoek Profiel',
            history_location: 'Locatie',
            history_foundation: 'Stichting',
            history_apex: 'Hoogtepunt',
            history_status: 'Status',
            history_bic: 'Cultureel Erfgoed (BIC)',
            history_intro_text_2: 'Hier kruisen wereldwijde stromen van oliehandel lokale tradities, waardoor een \"veldfabriek\" ontstond die ook als paleis diende.',
            history_timeline_1_desc: 'Rodrigo de Espinosa koopt het landgoed. Zijn familie controleert de olie- en zeephandel naar Indië.',
            history_timeline_2_desc: 'Onder Alonso de Ayala bereikt de hacienda zijn maximale productie. Duizenden olie-eenheden geëxporteerd naar Vlaanderen.',
            history_timeline_3_desc: 'Don Adrián Delgado Ayala herbouwt het landhuis \"vanaf de grond\". De huidige barokke indeling is geboren.',
            history_timeline_4_desc: 'De Engelse vlootblokkade van Cadiz snijdt Atlantische routes af. Zonder export gaat Ayala failliet.',
            history_timeline_5_desc: 'De familie Gómez de Barreda verwerft het landgoed. De kruistuin en paardenfresco\'s worden toegevoegd.',
            history_timeline_modern: '21e Eeuw',
            history_timeline_rebirth: 'Wedergeboorte',
            history_timeline_rebirth_desc: 'Onder toezicht van de gebroeders Maestre Benjumea worden originele esgrafiados onthuld. Overgang naar de belevingseconomie.',
            history_anatomy_title: 'Anatomie van een Hacienda',
            history_anatomy_subtitle: 'De perfecte fusie tussen industriële kracht en residentieel paleis.',
            history_arch_almazara: 'De Almazara',
            history_arch_tower: 'Contragewichttoren',
            history_arch_patios: 'Patiosysteem',
            history_arch_capilla: 'De Kapel',
            history_almazara_title: 'De Vloeibaar Goud Fabriek',
            history_almazara_desc: 'Dit immense schip huisvestte de \"spilbalk\", een houten leviatand van 15 meter.',
            history_tower_title: 'Contragewichttoren',
            history_tower_desc: 'De \"wolkenkrabbers\" van het Andalusische platteland. Pure fysica om het contragewicht te verankeren.',
            history_patios_title: 'Ruimtelijke Segregatie',
            history_patios_desc: 'Architectuur legt sociale orde op. De Arbeidspatio (2000 m²) bruist van activiteit.',
            history_capilla_title: 'Privé Oratorium',
            history_capilla_desc: 'Met zijn altaarstuk en Mariale tegels legitimeerde de kapel de vroomheid van de eigenaren.',
            history_economy_title: 'Oconomie van de Olie',
            history_production_mode: '18e Eeuwse Productie',
            history_labor_mode: 'Arbeidscyclus',
            history_chart_note: '*Geschatte historische gegevens.',
            history_social_title: 'Sociale Stratificatie',
            history_lordship: 'De Heerlijkheid (Señorío)',
            history_lordship_rank: 'Aristocratie',
            history_lordship_desc: 'Afwezige eigenaren die in Sevilla wonen. De hacienda was hun statussymbool.',
            history_housekeeper: 'De Beheerder (Casero)',
            history_housekeeper_rank: 'Beheer',
            history_housekeeper_desc: 'De aanwezige autoriteit. Bewaker van de sleutels van de graanschuur en de molen.',
            history_laborers: 'De Arbeiders (Gañanía)',
            history_laborers_rank: 'Arbeidskrachten',
            history_laborers_desc: 'Seizoensgebonden olijvenplukkers en herders die in gemeenschappelijke slaapzalen wonen.'
        },
        de: {
            nav_legend: 'Geschichte',
            nav_spaces: 'Räume',
            nav_inquire: 'Kontakt',
            hero_est: 'Gegründet im 16. Jahrhundert',
            hero_title1: 'SONNE.',
            hero_title2: 'STEIN.',
            hero_title3: 'FEIER.',
            hero_subtitle: 'Wo Geschichte zu Ihrer Kulisse wird.',
            hero_cta: 'Entdecken',
            legacy_section_title: 'Das Erbe',
            legacy_heading_1: 'Schatten',
            legacy_heading_2: 'und Licht',
            legacy_text_1: 'Manche Orte sind nur Räume. Dieser hat eine Geschichte—und jetzt ist er bereit für Ihre. Mauern, die seit der Rückkehr der Konquistadoren stehen. Eine Ölmühle, die Früchte für Imperien presste.',
            legacy_text_2: 'Wir haben den Putz entfernt, um die Seele des Gebäudes freizulegen. Roher Ziegel. Alter Stein. Dies ist kein verkleideter Festsaal. Es ist Geschichte, die Sie zum Feiern einlädt.',
            spaces_section_title: 'Die Bühne',
            spaces_subtitle: 'Wählen Sie Ihre Kulisse',
            space_almazara: 'Die Almazara',
            space_almazara_desc: 'Weit. Gewölbt. Eindrucksvoll. Die alte Ölmühle wiedergeboren. Hohe Decken, die das Echo des Lachens einfangen. Perfekt, wenn die Gästeliste groß ist und der Eindruck absolut sein muss.',
            space_almazara_cap: 'Kapazität: 500+',
            space_almazara_type: 'Typ: Innen / Großer Saal',
            space_gardens: 'Die Gärten',
            space_gardens_desc: 'Die Natur als Architekt. Mit Geschichte gepflasterte Patios, umgeben von Jasmin und dem Duft der Jahrhunderte. Eine Umgebung, die keine Dekoration braucht, nur Wertschätzung.',
            space_gardens_cap: 'Kapazität: 800+',
            space_gardens_type: 'Typ: Freiluft / Historische Patios',
            footer_cta1: 'RESERVIEREN SIE',
            footer_cta2: 'IHREN TERMIN',
            footer_title: 'Ihr Kapitel Beginnt',
            footer_role: 'Eventmanagerin',
            footer_location: 'Standort',
            footer_social: 'Soziale Medien',
            history_hero_title: 'Andalusisches Erbe',
            history_hero_subtitle: 'Architektur des Olivenöls und der Stille',
            weddings_hero_title: 'Ein historischer Roman',
            weddings_hero_subtitle: 'Kein Märchen',
            corporate_hero_title: 'Abschalten, um sich neu zu verbinden',
            corporate_hero_subtitle: 'Firmen-Retreats & Events',
            nav_discover_history: 'Geschichte Entdecken',
            weddings_ceremony_title: 'Die Zeremonie',
            weddings_ceremony_text: 'Vergessen Sie das plastiline \"und sie lebten glücklich bis ans Ende ihrer Tage\". Dies ist ein Steinstruktur, die Jahrhunderte gesehen hat. Unsere Patios sind keine Kulissen; sie sind Bühnen aus Schwerkraft und Licht.',
            corporate_focus_title: 'Isolation fördert Konzentration',
            corporate_focus_text: 'In einer Welt ständiger Benachrichtigungen ist wahrer Luxus die Stille. Die Hacienda La Soledad bietet eine schlichte, aber erhabene Umgebung, in der Teams vom Lärm abschalten können, um sich wieder auf ihr Ziel zu besinnen.',
            history_intro_title: 'Sozioökonomisches Palimpsest',
            history_intro_text: 'Die Hacienda de la Soledad ist mehr als nur ein einfaches Gebäude; sie ist ein Querschnitt der andalusischen Geschichte.',
            history_timeline_title: 'Säkulare Chronik',
            history_timeline_1_title: 'Gründung',
            history_timeline_2_title: 'Kommerzieller Aufschwung',
            history_timeline_3_title: 'Der große Wiederaufbau',
            history_timeline_4_title: 'Krieg & Ruin',
            history_timeline_5_title: 'Das Goldene Zeitalter',
            weddings_celebration_title: 'Die Feier',
            weddings_celebration_text: 'Die Almazara mit ihren Gewölbedecken und der perfekten Akustik verwandelt sich in den ultimativen Ballsaal. Kapazität für große Bankette, ohne die Atmosphäre der Exklusivität zu verlieren. Jede Ecke ist darauf ausgelegt, zu beeindrucken – nicht durch ihre Dekoration, sondern durch ihre Authentizität.',
            weddings_corners_title: 'Unsere Ecken',
            corporate_efficiency_title: 'Effizienz',
            corporate_efficiency_text: 'Schnelle Antworten. Minimale Bürokratie. Wir verstehen, dass ein Firmenevent keine Hochzeit ist; es ist eine Investition. Klare Dossiers, technische Pläne bereit und ein Team, das die Sprache der Wirtschaft spricht.',
            corporate_character_title: 'Charakter',
            corporate_character_text: 'Ersetzen Sie sterile Konferenzräume durch Mauern aus dem 16. Jahrhundert. Inspirieren Sie Ihre Führungskräfte mit dem Ernst der Geschichte. Die Architektur hier dekoriert nicht; sie gebietet Respekt.',
            corporate_map_title: 'Plan der Hacienda',
            corporate_map_text: 'Lernen Sie die genaue Verteilung unserer 10.000 m² an vielseitigen Flächen kennen.',
            corporate_view_detail: 'Detail Ansicht',
            corporate_download_map: 'Technischen Plan herunterladen (PDF)',
            corporate_mice_title: 'MICE & Teambuilding',
            corporate_mice_text: 'Von groß angelegten Kongressen in unserer Almazara bis hin zu intimen Rückzugsorten für Führungskräfte in den Gärten. Absolute Kapazität und Vielseitigkeit.',
            corporate_request_dossier: 'Business-Dossier anfordern',
            corporate_trusted_by: 'Vertrauen uns',
            spaces_indoor_title: 'Innenräume',
            spaces_indoor_subtitle: 'Klimatisiert. Historische Decken. Unvergleichliche Atmosphäre.',
            spaces_outdoor_title: 'Patios und Gärten',
            spaces_outdoor_subtitle: 'Albero. Stein. Offener Himmel.',
            spaces_tech_title: 'Technische Spezifikationen',
            spaces_tech_dossier: 'Technisches Dossier herunterladen',
            label_cocktail: 'Cocktail',
            label_banquet: 'Bankett',
            label_area: 'Fläche',
            label_height: 'Höhe',
            label_capacity: 'Kapazität',
            label_indoor_desc: 'Klimatisiert. Historische Decken. Unvergleichliche Atmosphäre.',
            label_outdoor_desc: 'Albero. Stein. Offener Himmel.',
            availability_title: 'Verfügbarkeit',
            availability_subtitle: 'Prüfen Sie verfügbare Termine für Ihre Feier. Grün markierte Daten sind für Reservierungen verfügbar.',
            availability_available: 'Verfügbar',
            availability_booked: 'Reserviert',
            availability_consultation: 'In Anfrage',
            availability_past: 'Vergangen',
            availability_request_info: 'Informationen anfordern',
            availability_whatsapp: 'Direktes WhatsApp',
            availability_selected_intro: 'Dieses Datum ist verfügbar. Möchten Sie weitere Informationen anfordern?',
            index_bridge_title: 'Zwei Welten, ein Dach.',
            index_bridge_subtitle: 'Intimität für Wenige. Größe für Viele.',
            index_weddings_title: 'Königliche Hochzeiten',
            index_weddings_text: 'Feiern Sie Ihre Verbindung in einem historischen Heiligtum. Von der gewölbten Almazara bis zu den jasmingefüllten Patios.',
            index_weddings_cta: 'Hochzeiten ansehen',
            index_corporate_title: 'Firmenveranstaltungen',
            index_corporate_text: 'Disconnect to reconnect. Executive-Retreats und Produkteinführungen in einer inspirierenden Umgebung.',
            index_corporate_cta: 'Unternehmen ansehen',
            index_follow_us: 'Folgen Sie uns',
            index_insta_placeholder: 'Ihr Instagram-Feed wird hier erscheinen',
            index_visit_profile: 'Profil besuchen',
            history_location: 'Standort',
            history_foundation: 'Gründung',
            history_apex: 'Höhepunkt',
            history_status: 'Status',
            history_bic: 'Kulturerbe (BIC)',
            history_intro_text_2: 'Hier kreuzen sich globale Warenströme von Öl mit lokalen Traditionen und schufen eine „Feldfabrik“, die auch als Schloss diente.',
            history_timeline_1_desc: 'Rodrigo de Espinosa kauft das Anwesen. Seine Familie kontrolliert den Öl- und Seifenhandel nach Indien.',
            history_timeline_2_desc: 'Unter Alonso de Ayala erreicht die Hacienda ihre maximale Produktion. Tausende Öleinheiten nach Flandern exportiert.',
            history_timeline_3_desc: 'Don Adrián Delgado Ayala baut das Herrenhaus „von Grund auf“ wieder auf. Der heutige barocke Grundriss entsteht.',
            history_timeline_4_desc: 'Die englische Seeblockade von Cádiz unterbricht die Atlantikrouten. Ohne Exporte geht Ayala bankrott.',
            history_timeline_5_desc: 'Die Familie Gómez de Barreda erwirbt das Anwesen. Der Kreuzungsgarten und Pferdefresken werden hinzugefügt.',
            history_timeline_modern: '21. Jahrhundert',
            history_timeline_rebirth: 'Wiedergeburt',
            history_timeline_rebirth_desc: 'Unter der Obhut der Brüder Maestre Benjumea werden originale Esgrafiados enthuld. Übergang zur Erlebnisökonomie.',
            history_anatomy_title: 'Anatomie einer Hacienda',
            history_anatomy_subtitle: 'Die perfekte Verschmelzung von industrieller Kraft und Wohnpalast.',
            history_arch_almazara: 'Die Almazara',
            history_arch_tower: 'Gegengewichtsturm',
            history_arch_patios: 'Patiosystem',
            history_arch_capilla: 'Die Kapelle',
            history_almazara_title: 'Die Fabrik für flüssiges Gold',
            history_almazara_desc: 'Dieses riesige Schiff beherbergte den „Spindelbalken“, einen 15 Meter langen Holz-Leviathan.',
            history_tower_title: 'Gegengewichtsturm',
            history_tower_desc: 'Die „Wolkenkratzer“ der andalusischen Landschaft. Pure Physik zur Verankerung des Gegengewichts.',
            history_patios_title: 'Räumliche Trennung',
            history_patios_desc: 'Architektur erzwingt soziale Ordnung. Der Arbeitspatio (2000 m²) strotzt vor Aktivität.',
            history_capilla_title: 'Privates Oratorium',
            history_capilla_desc: 'Mit seinem Altarbild und den marianischen Kacheln legitimierte die Kapelle die Frömmigkeit der Besitzer.',
            history_economy_title: 'Öl-Wirtschaft',
            history_production_mode: 'Produktion im 18. Jahrhundert',
            history_labor_mode: 'Arbeitszyklus',
            history_chart_note: '*Geschätzte historische Daten.',
            history_social_title: 'Soziale Schichtung',
            history_lordship: 'Die Herrschaft (Señorío)',
            history_lordship_rank: 'Aristokratie',
            history_lordship_desc: 'Abwesende Besitzer, die in Sevilla lebten. Die Hacienda war ihr Statussymbol.',
            history_housekeeper: 'Der Verwalter (Casero)',
            history_housekeeper_rank: 'Management',
            history_housekeeper_desc: 'Die präsente Autorität. Wächter der Schlüssel für Kornspeicher und Mühle.',
            history_laborers: 'Die Arbeiter (Gañanía)',
            history_laborers_rank: 'Arbeitskräfte',
            history_laborers_desc: 'Saisonale Olivenpflücker und Hirten, die in Gemeinschaftsschlafsälen lebten.'
        }
    },
    
    // UI Logic
    reveal() {
        const reveals = document.querySelectorAll('.reveal-on-scroll');
        for (let i = 0; i < reveals.length; i++) {
            const windowHeight = window.innerHeight;
            const elementTop = reveals[i].getBoundingClientRect().top;
            const elementVisible = 150;
            if (elementTop < windowHeight - elementVisible) {
                reveals[i].classList.add('reveal-visible');
            }
        }
    },

    init() {
        this.reveal();
    }
})
