export default () => ({
    mobileMenuOpen: false, 
    scrolled: false,
    lang: 'es', // Default to Spanish as it is a Seville hacienda
    translations: {
        en: {
            nav_legend: 'History',
            nav_spaces: 'Spaces',
            nav_inquire: 'Inquire',
            hero_est: 'Est. XVI Century',
            hero_title1: 'SUN.',
            hero_title2: 'STONE.',
            hero_title3: 'CELEBRATION.',
            hero_subtitle: 'Where history becomes your backdrop.',
            hero_cta: 'Explore',
            legacy_section_title: 'The Legacy',
            legacy_heading_1: 'Shadow',
            legacy_heading_2: '& Light',
            legacy_text_1: 'Some places are merely venues. This one has a story—and now it\'s ready for yours. Walls that have stood since the conquistadors returned. An olive oil mill that crushed fruit for empires.',
            legacy_text_2: 'We stripped away the plaster to reveal the soul of the building. Raw brick. Ancient stone. This is not a venue dressed up for a party. It is history inviting you to celebrate.',
            spaces_section_title: 'The Stage',
            spaces_subtitle: 'Choose your backdrop',
            space_almazara: 'The Almazara',
            space_almazara_desc: 'Vast. Vaulted. Visceral. The old oil mill reborn. High ceilings that catch the echo of laughter. Perfect when the guest list is immense and the impression must be absolute.',
            space_almazara_cap: 'Capacity: 500+',
            space_almazara_type: 'Type: Indoor / Grand Hall',
            space_gardens: 'The Gardens',
            space_gardens_desc: 'Nature as the architect. Patios paved with history, surrounded by jasmine and the scent of centuries. A setting that requires no decoration, only appreciation.',
            space_gardens_cap: 'Capacity: 800+',
            space_gardens_type: 'Type: Open Air / Historical Patios',
            footer_cta1: 'RESERVE YOUR',
            footer_cta2: 'DATE',
            footer_title: 'Your Chapter Begins',
            footer_role: 'Event Director',
            footer_location: 'Location',
            footer_social: 'Social'
        },
        es: {
            nav_legend: 'Historia',
            nav_spaces: 'Espacios',
            nav_inquire: 'Contactar',
            hero_est: 'Est. Siglo XVI',
            hero_title1: 'SOL.',
            hero_title2: 'PIEDRA.',
            hero_title3: 'CELEBRACIÓN.',
            hero_subtitle: 'Donde la historia se convierte en tu escenario.',
            hero_cta: 'Explorar',
            legacy_section_title: 'El Legado',
            legacy_heading_1: 'Sombra',
            legacy_heading_2: 'y Luz',
            legacy_text_1: 'Algunos lugares son solo espacios. Este tiene una historia—y ahora está listo para la tuya. Muros que han permanecido desde el regreso de los conquistadores. Una almazara que prensó el fruto para imperios.',
            legacy_text_2: 'Quitamos el yeso para revelar el alma del edificio. Ladrillo crudo. Piedra antigua. Esto no es un salón de fiestas disfrazado. Es la historia invitándote a celebrar.',
            spaces_section_title: 'El Escenario',
            spaces_subtitle: 'Elige tu telón de fondo',
            space_almazara: 'La Almazara',
            space_almazara_desc: 'Vasta. Abovedada. Visceral. El antiguo molino renacido. Techos altos que capturan el eco de las risas. Perfecto cuando la lista de invitados es inmensa y la impresión debe ser absoluta.',
            space_almazara_cap: 'Capacidad: 500+',
            space_almazara_type: 'Tipo: Interior / Gran Salón',
            space_gardens: 'Los Jardines',
            space_gardens_desc: 'La naturaleza como arquitecto. Patios pavimentados con historia, rodeados de jazmín y el aroma de los siglos. Un escenario que no requiere decoración, solo admiración.',
            space_gardens_cap: 'Capacidad: 800+',
            space_gardens_type: 'Tipo: Aire Libre / Patios Históricos',
            footer_cta1: 'RESERVA TU',
            footer_cta2: 'FECHA',
            footer_title: 'Tu Capítulo Comienza',
            footer_role: 'Directora de Eventos',
            footer_location: 'Ubicación',
            footer_social: 'Redes'
        },
        fr: {
            nav_legend: 'Histoire',
            nav_spaces: 'Espaces',
            nav_inquire: 'Contact',
            hero_est: 'Fondée au XVIe Siècle',
            hero_title1: 'SOLEIL.',
            hero_title2: 'PIERRE.',
            hero_title3: 'CÉLÉBRATION.',
            hero_subtitle: 'Où l\'histoire devient votre décor.',
            hero_cta: 'Découvrir',
            legacy_section_title: 'L\'Héritage',
            legacy_heading_1: 'Ombre',
            legacy_heading_2: 'et Lumière',
            legacy_text_1: 'Certains lieux ne sont que des espaces. Celui-ci a une histoire—et maintenant, il est prêt pour la vôtre. Des murs debout depuis le retour des conquistadors. Un moulin à huile qui broyait les fruits pour des empires.',
            legacy_text_2: 'Nous avons retiré le plâtre pour révéler l\'âme du bâtiment. Brique brute. Pierre ancienne. Ce n\'est pas une salle de réception déguisée. C\'est l\'histoire qui vous invite à célébrer.',
            spaces_section_title: 'La Scène',
            spaces_subtitle: 'Choisissez votre décor',
            space_almazara: 'L\'Almazara',
            space_almazara_desc: 'Vaste. Voûtée. Viscérale. L\'ancien moulin renaît. De hauts plafonds qui capturent l\'écho des rires. Parfait quand la liste des invités est immense et l\'impression doit être absolue.',
            space_almazara_cap: 'Capacité : 500+',
            space_almazara_type: 'Type : Intérieur / Grande Salle',
            space_gardens: 'Les Jardins',
            space_gardens_desc: 'La nature comme architecte. Des patios pavés d\'histoire, entourés de jasmin et du parfum des siècles. Un cadre qui n\'exige aucune décoration, seulement de l\'admiration.',
            space_gardens_cap: 'Capacité : 800+',
            space_gardens_type: 'Type : Plein Air / Patios Historiques',
            footer_cta1: 'RÉSERVEZ VOTRE',
            footer_cta2: 'DATE',
            footer_title: 'Votre Chapitre Commence',
            footer_role: 'Directrice Événementielle',
            footer_location: 'Adresse',
            footer_social: 'Réseaux'
        },
        nl: {
            nav_legend: 'Geschiedenis',
            nav_spaces: 'Ruimtes',
            nav_inquire: 'Contact',
            hero_est: 'Gesticht in de 16e Eeuw',
            hero_title1: 'ZON.',
            hero_title2: 'STEEN.',
            hero_title3: 'VIERING.',
            hero_subtitle: 'Waar geschiedenis jouw achtergrond wordt.',
            hero_cta: 'Ontdekken',
            legacy_section_title: 'Het Erfgoed',
            legacy_heading_1: 'Schaduw',
            legacy_heading_2: 'en Licht',
            legacy_text_1: 'Sommige plaatsen zijn slechts ruimtes. Deze heeft een verhaal—en nu is het klaar voor dat van jou. Muren die overeind staan sinds de terugkeer van de conquistadores. Een olijfoliemolen die vruchten perste voor keizerrijken.',
            legacy_text_2: 'We hebben het pleisterwerk verwijderd om de ziel van het gebouw te onthullen. Ruwe baksteen. Oude steen. Dit is geen verklede feestzaal. Het is geschiedenis die je uitnodigt om te vieren.',
            spaces_section_title: 'Het Podium',
            spaces_subtitle: 'Kies jouw achtergrond',
            space_almazara: 'De Almazara',
            space_almazara_desc: 'Wijd. Gewelfd. Indrukwekkend. De oude olijfmolen herboren. Hoge plafonds die de echo van gelach vangen. Ideaal wanneer de gastenlijst enorm is en de indruk absoluut moet zijn.',
            space_almazara_cap: 'Capaciteit: 500+',
            space_almazara_type: 'Type: Binnen / Grote Zaal',
            space_gardens: 'De Tuinen',
            space_gardens_desc: 'De natuur als architect. Patio\'s geplaveid met geschiedenis, omringd door jasmijn en de geur van eeuwen. Een omgeving die geen decoratie nodig heeft, alleen waardering.',
            space_gardens_cap: 'Capaciteit: 800+',
            space_gardens_type: 'Type: Openlucht / Historische Patio\'s',
            footer_cta1: 'RESERVEER JE',
            footer_cta2: 'DATUM',
            footer_title: 'Jouw Hoofdstuk Begint',
            footer_role: 'Evenementenmanager',
            footer_location: 'Locatie',
            footer_social: 'Social Media'
        },
        de: {
            nav_legend: 'Geschichte',
            nav_spaces: 'Räume',
            nav_inquire: 'Kontakt',
            hero_est: 'Gegründet im 16. Jahrhundert',
            hero_title1: 'SONNE.',
            hero_title2: 'STEIN.',
            hero_title3: 'FEIER.',
            hero_subtitle: 'Wo Geschichte zu Ihrer Kulisse wird.',
            hero_cta: 'Entdecken',
            legacy_section_title: 'Das Erbe',
            legacy_heading_1: 'Schatten',
            legacy_heading_2: 'und Licht',
            legacy_text_1: 'Manche Orte sind nur Räume. Dieser hat eine Geschichte—und jetzt ist er bereit für Ihre. Mauern, die seit der Rückkehr der Konquistadoren stehen. Eine Ölmühle, die Früchte für Imperien presste.',
            legacy_text_2: 'Wir haben den Putz entfernt, um die Seele des Gebäudes freizulegen. Roher Ziegel. Alter Stein. Dies ist kein verkleideter Festsaal. Es ist Geschichte, die Sie zum Feiern einlädt.',
            spaces_section_title: 'Die Bühne',
            spaces_subtitle: 'Wählen Sie Ihre Kulisse',
            space_almazara: 'Die Almazara',
            space_almazara_desc: 'Weit. Gewölbt. Eindrucksvoll. Die alte Ölmühle wiedergeboren. Hohe Decken, die das Echo des Lachens einfangen. Perfekt, wenn die Gästeliste groß ist und der Eindruck absolut sein muss.',
            space_almazara_cap: 'Kapazität: 500+',
            space_almazara_type: 'Typ: Innen / Großer Saal',
            space_gardens: 'Die Gärten',
            space_gardens_desc: 'Die Natur als Architekt. Mit Geschichte gepflasterte Patios, umgeben von Jasmin und dem Duft der Jahrhunderte. Eine Umgebung, die keine Dekoration braucht, nur Wertschätzung.',
            space_gardens_cap: 'Kapazität: 800+',
            space_gardens_type: 'Typ: Freiluft / Historische Patios',
            footer_cta1: 'RESERVIEREN SIE',
            footer_cta2: 'IHREN TERMIN',
            footer_title: 'Ihr Kapitel Beginnt',
            footer_role: 'Eventmanagerin',
            footer_location: 'Standort',
            footer_social: 'Soziale Medien'
        }
    },
    t(key) {
        return this.translations[this.lang][key] || key;
    },
    
    // UI Logic
    reveal() {
        const reveals = document.querySelectorAll('.reveal-on-scroll');
        for (let i = 0; i < reveals.length; i++) {
            const windowHeight = window.innerHeight;
            const elementTop = reveals[i].getBoundingClientRect().top;
            const elementVisible = 150;
            if (elementTop < windowHeight - elementVisible) {
                reveals[i].classList.add('reveal-visible');
            }
        }
    },

    init() {
        this.reveal();
    }
})
